import type {
  BlogPost,
  Category,
  GalleryItem,
  Inquiry,
  Product,
  Project,
  Service,
  SiteSettings,
} from "./types";

export const siteSettings: SiteSettings = {
  companyName: "Satya Power Technologys",
  tagline: "Fiber Optic Tools & Services for AP & Telangana",
  phone: "+91 95428 40444",
  whatsapp: "919542840444",
  email: "info@satyapowertechnologys.in",
  address: "Hyderabad · Vijayawada · Kakinada · Srikakulam · Tirupathi",
  social: {
    instagram: "https://www.instagram.com/satya_power_technologys",
    youtube: "https://youtube.com/@satyapowertechnologys",
  },
};

export const categories: Category[] = [
  { id: "c1", slug: "fusion-splicers", name: "Fusion Splicers", description: "Precision core & cladding alignment splicers." },
  { id: "c2", slug: "otdr", name: "OTDR", description: "Optical Time Domain Reflectometers for testing." },
  { id: "c3", slug: "power-meters", name: "Power Meters", description: "Optical power measurement instruments." },
  { id: "c4", slug: "cleavers", name: "Cleavers", description: "High-precision fiber cleavers." },
  { id: "c5", slug: "vfl", name: "Visual Fault Locators", description: "Red-light fault locators for fiber." },
  { id: "c6", slug: "toolkits", name: "Toolkits", description: "Professional fiber optic toolkits." },
];

export const brands = ["INNO", "Grandway", "Claron", "EXFO", "VIAVI", "SKL"];

export const products: Product[] = [
  {
    id: "p1",
    slug: "inno-view-7-fusion-splicer",
    name: "INNO View 7 Fusion Splicer",
    brand: "INNO",
    categoryId: "c1",
    categoryName: "Fusion Splicers",
    shortDescription: "Active-clad alignment fusion splicer with rugged build and 5\" touchscreen.",
    description:
      "The INNO View 7 delivers precision splicing with active clad alignment, ideal for FTTH and enterprise deployments. Rugged IP-rated body, fast splicing and heating cycles.",
    features: [
      "Active clad alignment",
      "5-inch touchscreen",
      "Splice time ~7 seconds",
      "Heat time ~13 seconds",
      "IP-rated rugged body",
    ],
    specs: {
      "Splice Loss": "0.02 dB (SM)",
      "Splice Time": "7s",
      "Heat Time": "13s",
      Display: "5\" Touchscreen",
      Battery: "300 cycles",
    },
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200",
    featured: true,
    createdAt: "2025-01-10",
  },
  {
    id: "p2",
    slug: "inno-view-3-fusion-splicer",
    name: "INNO View 3 Fusion Splicer",
    brand: "INNO",
    categoryId: "c1",
    categoryName: "Fusion Splicers",
    shortDescription: "Compact active-clad splicer for FTTH technicians.",
    description: "Compact and lightweight fusion splicer built for daily FTTH work.",
    features: ["Active clad alignment", "Compact build", "Fast splicing"],
    specs: { "Splice Loss": "0.02 dB (SM)", "Splice Time": "9s", Battery: "250 cycles" },
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200",
    featured: true,
    createdAt: "2025-02-05",
  },
  {
    id: "p3",
    slug: "viavi-mts-2000-otdr",
    name: "VIAVI MTS-2000 OTDR",
    brand: "VIAVI",
    categoryId: "c2",
    categoryName: "OTDR",
    shortDescription: "Modular handheld OTDR platform for field testing.",
    description: "The VIAVI MTS-2000 is a modular test platform supporting a wide range of OTDR modules.",
    features: ["Modular platform", "Long dynamic range", "Touchscreen UI"],
    specs: { "Dynamic Range": "42 dB", Wavelengths: "1310/1550 nm" },
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=1200",
    featured: true,
    createdAt: "2025-01-20",
  },
  {
    id: "p4",
    slug: "exfo-maxtester-730c-otdr",
    name: "EXFO MaxTester 730C OTDR",
    brand: "EXFO",
    categoryId: "c2",
    categoryName: "OTDR",
    shortDescription: "Rugged handheld OTDR for FTTx and access networks.",
    description: "Purpose-built for FTTx, the MaxTester 730C is easy to use and highly rugged.",
    features: ["FTTx optimized", "iOLM support", "Rugged build"],
    specs: { "Dynamic Range": "39 dB", Wavelengths: "1310/1550/1625 nm" },
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=1200",
    featured: true,
    createdAt: "2025-03-01",
  },
  {
    id: "p5",
    slug: "grandway-fhp2a04-power-meter",
    name: "Grandway FHP2A04 Power Meter",
    brand: "Grandway",
    categoryId: "c3",
    categoryName: "Power Meters",
    shortDescription: "Handheld optical power meter with wide dynamic range.",
    description: "Reliable and affordable power meter for daily field measurements.",
    features: ["Wide dynamic range", "Auto wavelength ID", "USB charging"],
    specs: { Range: "-70 to +10 dBm", Wavelengths: "800–1700 nm" },
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200",
    featured: true,
    createdAt: "2025-02-14",
  },
  {
    id: "p6",
    slug: "skl-6c-high-precision-cleaver",
    name: "SKL-6C High-Precision Cleaver",
    brand: "SKL",
    categoryId: "c4",
    categoryName: "Cleavers",
    shortDescription: "16-position blade cleaver for consistent fiber end faces.",
    description: "High precision cleaver with a long-life blade delivering consistent low cleave angles.",
    features: ["16 blade positions", "Sub-0.5° cleave angle", "Long blade life"],
    specs: { "Blade Life": "48,000 cleaves", "Cleave Angle": "≤0.5°" },
    image: "https://images.unsplash.com/photo-1517420704952-d9f39e95b43e?w=1200",
    featured: true,
    createdAt: "2025-01-25",
  },
  {
    id: "p7",
    slug: "vfl-30-visual-fault-locator",
    name: "VFL-30 Visual Fault Locator",
    brand: "Satya Power",
    categoryId: "c5",
    categoryName: "Visual Fault Locators",
    shortDescription: "30 mW visual fault locator with long-range detection.",
    description: "Locate breaks, bends, and connector faults quickly with strong red-light output.",
    features: ["30 mW output", "Continuous & flash modes", "Rugged aluminium body"],
    specs: { Output: "30 mW", Wavelength: "650 nm", Range: "20 km" },
    image: "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=1200",
    featured: true,
    createdAt: "2025-02-18",
  },
  {
    id: "p8",
    slug: "professional-fiber-optic-toolkit",
    name: "Professional Fiber Optic Toolkit",
    brand: "Satya Power",
    categoryId: "c6",
    categoryName: "Toolkits",
    shortDescription: "Complete toolkit for FTTH & enterprise fiber installations.",
    description: "Everything a technician needs in one rugged case: strippers, cleavers, cleaning tools and more.",
    features: ["30+ tools included", "Rugged carry case", "Field-ready"],
    specs: { "Tool Count": "30+", Case: "Rugged ABS" },
    image: "https://images.unsplash.com/photo-1580894742597-87bc8789db3d?w=1200",
    featured: true,
    createdAt: "2025-03-08",
  },
];

export const services: Service[] = [
  {
    id: "s1",
    slug: "fusion-splicer-repair",
    title: "Fusion Splicer Repair & Calibration",
    summary: "Factory-grade repair, calibration and electrode replacement for all major brands.",
    description:
      "In-house factory-trained technicians repair, calibrate and service fusion splicers with genuine parts and precise alignment testing.",
    icon: "Wrench",
  },
  {
    id: "s2",
    slug: "otdr-service",
    title: "OTDR Service & Calibration",
    summary: "Diagnostics, module repair and NABL-traceable calibration for OTDRs.",
    description: "Complete diagnostic, module-level repair and calibration for VIAVI, EXFO and INNO OTDRs.",
    icon: "Activity",
  },
  {
    id: "s3",
    slug: "on-site-support",
    title: "On-site Support",
    summary: "Emergency response across AP & Telangana within hours.",
    description: "Field engineers deployed to your site for critical repair and installation work.",
    icon: "Truck",
  },
  {
    id: "s4",
    slug: "amc-contracts",
    title: "AMC Contracts",
    summary: "Annual maintenance contracts tailored to your fleet.",
    description: "Predictable pricing, priority response and free calibration under a yearly plan.",
    icon: "ShieldCheck",
  },
  {
    id: "s5",
    slug: "ev-battery-repair",
    title: "EV Battery Repair & Service",
    summary: "Diagnostics, safety testing and capacity restoration for EV batteries.",
    description: "Comprehensive health diagnostics, safety testing, capacity validation and servicing to restore battery efficiency.",
    icon: "BatteryCharging",
  },
  {
    id: "s6",
    slug: "cell-replacement",
    title: "EV Battery Cell Replacement",
    summary: "Cost-effective replacement of degraded cell modules.",
    description: "Replace individual degraded cell modules to extend the lifecycle of your pack.",
    icon: "Zap",
  },
];

export const projects: Project[] = [
  {
    id: "pr1",
    slug: "ftth-rollout-hyderabad",
    title: "FTTH Rollout — Hyderabad Metro",
    client: "Regional ISP",
    location: "Hyderabad",
    year: 2024,
    summary: "Supplied splicing and testing equipment for a 40,000-home FTTH build-out.",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200",
    category: "FTTH",
  },
  {
    id: "pr2",
    slug: "backbone-upgrade-vijayawada",
    title: "Backbone Upgrade — Vijayawada",
    client: "State Data Center",
    location: "Vijayawada",
    year: 2024,
    summary: "OTDR testing and certification of 220 km inter-city dark fiber backbone.",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200",
    category: "Backbone",
  },
  {
    id: "pr3",
    slug: "campus-network-kakinada",
    title: "Campus Network — Kakinada",
    client: "Engineering College",
    location: "Kakinada",
    year: 2023,
    summary: "End-to-end passive optical network for a 5,000-student campus.",
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200",
    category: "Enterprise",
  },
  {
    id: "pr4",
    slug: "ev-fleet-service-tirupati",
    title: "EV Fleet Battery Service — Tirupathi",
    client: "Mobility Operator",
    location: "Tirupathi",
    year: 2025,
    summary: "Diagnostics and cell replacement for a fleet of 80 electric three-wheelers.",
    image: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=1200",
    category: "EV",
  },
  {
    id: "pr5",
    slug: "smart-city-srikakulam",
    title: "Smart City Fiber — Srikakulam",
    client: "Municipal Corporation",
    location: "Srikakulam",
    year: 2023,
    summary: "Splicing, testing and commissioning for smart-city surveillance backbone.",
    image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1200",
    category: "Government",
  },
  {
    id: "pr6",
    slug: "isp-deployment-nellore",
    title: "ISP Deployment — Nellore",
    client: "Local ISP",
    location: "Nellore",
    year: 2022,
    summary: "Turnkey equipment supply and staff training for a new regional ISP.",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1200",
    category: "FTTH",
  },
];

export const gallery: GalleryItem[] = [
  { id: "g1", title: "Fusion Splicer Service", image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=900", category: "Service" },
  { id: "g2", title: "Field Engineering", image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=900", category: "Field" },
  { id: "g3", title: "Hyderabad Branch", image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=900", category: "Branches" },
  { id: "g4", title: "Toolkit Assembly", image: "https://images.unsplash.com/photo-1580894742597-87bc8789db3d?w=900", category: "Products" },
  { id: "g5", title: "OTDR Testing", image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=900", category: "Service" },
  { id: "g6", title: "EV Battery Lab", image: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=900", category: "EV" },
  { id: "g7", title: "Training Session", image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=900", category: "Training" },
  { id: "g8", title: "Kakinada Team", image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=900", category: "Team" },
  { id: "g9", title: "Cable Prep", image: "https://images.unsplash.com/photo-1517420704952-d9f39e95b43e?w=900", category: "Field" },
];

export const blogPosts: BlogPost[] = [
  {
    id: "b1",
    slug: "choosing-right-fusion-splicer",
    title: "How to choose the right fusion splicer for FTTH",
    excerpt: "A practical guide to picking between active clad and core alignment splicers.",
    content: "Full article content...",
    cover: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200",
    author: "Satya Team",
    publishedAt: "2025-04-12",
    tags: ["FTTH", "Splicers"],
  },
  {
    id: "b2",
    slug: "otdr-basics",
    title: "OTDR basics: reading traces like a pro",
    excerpt: "Learn to interpret events, reflections and losses from OTDR traces.",
    content: "Full article content...",
    cover: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=1200",
    author: "Satya Team",
    publishedAt: "2025-03-18",
    tags: ["OTDR", "Training"],
  },
  {
    id: "b3",
    slug: "ev-battery-care",
    title: "Extending EV battery lifecycle with cell-level service",
    excerpt: "Why replacing individual cells is smarter than swapping the full pack.",
    content: "Full article content...",
    cover: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=1200",
    author: "Satya Team",
    publishedAt: "2025-02-20",
    tags: ["EV", "Service"],
  },
];

export const inquiries: Inquiry[] = [
  {
    id: "i1",
    name: "K. Raghunath",
    email: "raghu@example.com",
    phone: "+91 90000 11111",
    subject: "Bulk order — INNO View 7",
    message: "Need a quote for 5 units. Please share pricing.",
    status: "new",
    createdAt: "2025-07-10",
  },
  {
    id: "i2",
    name: "Mohammad Ali",
    email: "ali@example.com",
    phone: "+91 90000 22222",
    subject: "EXFO OTDR calibration",
    message: "Our OTDR needs annual calibration, please advise.",
    status: "read",
    createdAt: "2025-07-08",
  },
  {
    id: "i3",
    name: "P. Srinivas Rao",
    email: "psr@example.com",
    phone: "+91 90000 33333",
    subject: "Toolkit order",
    message: "Interested in 10 professional toolkits.",
    status: "resolved",
    createdAt: "2025-07-01",
  },
];

export const branches = [
  { city: "Hyderabad", type: "Sales & Service Branch", phone: "+91 86881 51526", image: "https://images.unsplash.com/photo-1596622932569-c5d43b76e5f1?w=900" },
  { city: "Vijayawada", type: "Sales & Service Branch", phone: "+91 86624 78901", image: "https://images.unsplash.com/photo-1590254553792-7a83a9bfd0b1?w=900" },
  { city: "Kakinada", type: "Sales & Service Branch", phone: "+91 95428 40444", image: "https://images.unsplash.com/photo-1548013146-72479768bada?w=900" },
  { city: "Srikakulam", type: "Service Support", phone: "+91 89424 56789", image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=900" },
  { city: "Tirupathi", type: "Service Support", phone: "+91 95428 40444", image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=900" },
];
